import { UnitsState } from "./unitSlice";

export const initialUnits: UnitsState = {
  units: [
    {
      id: "rocket",
      name: "Scout Rocket",
      order: 1,
      resourceCost: [
        { resourceId: "money", name: "Money", quantity: 100 },
        { resourceId: "productionCapacity", name: "Production Capacity", quantity: 1 },
      ],
      resourceOutput: [
        { resourceId: "tonsInSpace", name: "Tons in Space", quantity: 0.25 },
        { resourceId: "spaceCapacity", name: "Space Capacity", quantity: 0.25 },
      ],
      unitCost: [],
      isVisible: true,
      quantity: 0,
      level: 0,
      buttonState: "disabled",
      levelCost: 10000,
      requiredUnits: [],
      attributes: [],
      upgrades: [
        {
          id: "rocket.advanced",
          name: "Mildly Reusable Larger Rockets",
          new_unit_name: "Space Shuttle",
          log_message: "Rocket advanced upgrade applied",
          description:
            "Let's try to reuse rockets. Decrease cost of rockets by 50%",
          order: 1,
          isVisible: false,
          isApplied: false,
          resourceCostUpdate: [{ resourceId: "money", name: "Money", quantity: 0.5 }],
          resourceCost: [
            { unitId: "money", name: "Money", quantity: 192000000000 },
            { unitId: "productionCapacity", name: "Production Capacity", quantity: 1 },
          ],
          resourceOutputUpdate: [{ resourceId: "tonsInSpace", name: "Tons in Space", quantity: 25 }],
          requiredUnits: [],
          requiredResources: [{ unitId: "tonsInSpace", name: "Tons in Space", quantity: 10 }],
        },
        {
          id: "rocket.partialReusable",
          name: "Actually Partially Reusable Rockets",
          new_unit_name: "Falcon 9",
          log_message: "Partially reusing rockets upgrade applied",
          description:
            "If we actually reuse rockets, we can decrease cost of rockets by 90%.",
          order: 2,
          isVisible: false,
          isApplied: false,
          resourceCostUpdate: [{ resourceId: "money", name: "Money", quantity: 0.1 }],
          resourceCost: [{ unitId: "money", name: "Money", quantity: 10000000000 }],
          resourceOutputUpdate: [{ resourceId: "tonsInSpace", name: "Tons in Space", quantity: 25 }],
          requiredUnits: [],
          requiredResources: [{ unitId: "tonsInSpace", name: "Tons in Space", quantity: 10 }],
        },
        {
          id: "rocket.fullyReusable",
          name: "Fully Reusable Rockets",
          new_unit_name: "Starship",
          log_message: "Fully reusing rockets upgrade applied",
          description:
            "It turns out throwing away rockets is a bad idea. Decrease cost of rockets another 90%.",
          order: 3,
          isVisible: false,
          isApplied: false,
          resourceCostUpdate: [{ resourceId: "money", name: "Money", quantity: 0.1 }],
          resourceCost: [{ unitId: "money", name: "Money", quantity: 10000000000 }],
          resourceOutputUpdate: [
            { resourceId: "tonsInSpace", name: "Tons in Space", quantity: 100 },
            { resourceId: "spaceCapacity", name: "Space Capacity", quantity: 100 },
          ],
          requiredUnits: [],
          requiredResources: [{ unitId: "tonsInSpace", name: "Tons in Space", quantity: 20 }],
        },
      ],
    },
    {
      id: "economy",
      name: "Economy",
      order: 2,
      resourceCost: [{ resourceId: "spaceCapacity", name: "Space Capacity", quantity: 0.25 }],
      resourceOutput: [{ resourceId: "money", name: "Money", quantity: 1000 }],
      unitCost: [],
      isVisible: true,
      quantity: 0,
      level: 0,
      buttonState: "disabled",
      levelCost: 0,
      requiredUnits: [{ unitId: "rocket", name: "Rockets", quantity: 10 }],
      attributes: [],
      upgrades: [
        {
          id: "economy.satellites",
          name: "Commercial Satellites",
          new_unit_name: "Economy",
          log_message: "more demand for satellites",
          description:
            "Commercial satellites increase the demand for tons in space, beyond govenerment contracts.",
          order: 1,
          isVisible: false,
          isApplied: false,
          resourceCostUpdate: [{ resourceId: "tonsInSpace", name: "Tons in Space", quantity: 1 }],
          resourceCost: [{ unitId: "tonsInSpace", name: "Tons in Space", quantity: 100 }],
          resourceOutputUpdate: [{ resourceId: "money", name: "Money", quantity: 2 }],
          requiredUnits: [],
          requiredResources: [{ unitId: "money", name: "Money", quantity: 1 }],
        },
      ],
    },
    {
      id: "human",
      name: "Humans",
      order: 3,
      resourceCost: [{ resourceId: "money", name: "Money", quantity: 100 }],
      resourceOutput: [{ resourceId: "productionCapacity", name: "Production Capacity", quantity: 1 }],
      unitCost: [],
      isVisible: true,
      quantity: 7880000000,
      level: 0,
      buttonState: "disabled",
      levelCost: 0,
      requiredUnits: [],
      attributes: [
        { name: "Lifespan", quantity: 73.4 },
        { name: "Education Level", quantity: 0 },
        { name: "Inspiration Level", quantity: 0 },
        { name: "productionRate", quantity: 1 },
      ],
      upgrades: [
        {
          id: "human.satellites",
          name: "Upgrade 1",
          new_unit_name: "Humans",
          description: "Life and stuff",
          log_message: "Human upgrade 1 applied",
          order: 1,
          isVisible: false,
          isApplied: false,
          resourceCostUpdate: [{ resourceId: "tonsInSpace", name: "Tons in Space", quantity: 1 }],
          resourceCost: [{ unitId: "tonsInSpace", name: "Tons in Space", quantity: 100 }],
          resourceOutputUpdate: [{ resourceId: "money", name: "Money", quantity: 2 }],
          requiredUnits: [],
          requiredResources: [{ unitId: "money", name: "Money", quantity: 1 }],
        },
        {
          id: "human.satellites",
          name: "Upgrade 2",
          new_unit_name: "Humans",
          description: "more stuff",
          log_message: "Human upgrade 2 applied",
          order: 1,
          isVisible: false,
          isApplied: false,
          resourceCostUpdate: [{ resourceId: "tonsInSpace", name: "Tons in Space", quantity: 1 }],
          resourceCost: [{ unitId: "tonsInSpace", name: "Tons in Space", quantity: 100 }],
          resourceOutputUpdate: [{ resourceId: "money", name: "Money", quantity: 2 }],
          requiredUnits: [],
          requiredResources: [{ unitId: "money", name: "Money", quantity: 1 }],
        },
      ],
    },
    {
      id: "science",
      name: "Science",
      order: 4,
      resourceCost: [],
      resourceOutput: [],
      unitCost: [],
      isVisible: true,
      quantity: 1,
      level: 0,
      buttonState: "disabled",
      levelCost: 0,
      requiredUnits: [],
      attributes: [
        { name: "Biology", quantity: 0 },
        { name: "Physics", quantity: 0 },
        { name: "Engineering", quantity: 0 },
      ],
      upgrades: [],
    },
    {
      id: "energy",
      name: "Energy",
      order: 5,
      resourceCost: [
        { resourceId: "money", name: "Money", quantity: 1 },
        { resourceId: "productionCapacity", name: "Production Capacity", quantity: 1 },
      ],
      resourceOutput: [{ resourceId: "energy", name: "Energy", quantity: 10 }],
      unitCost: [],
      isVisible: true,
      quantity: 0,
      level: 0,
      buttonState: "disabled",
      levelCost: 50000,
      requiredUnits: [{ unitId: "science", name: "Science", quantity: 1 }],
      attributes: [
        { name: "Fossil", quantity: 18.1 },
        { name: "Renewables", quantity: 7.9 },
        { name: "Fission", quantity: 2.6 },
        { name: "Storage", quantity: 0.0001 },
      ],
      upgrades: [
        {
          id: "energy.solar",
          name: "Solar Power",
          new_unit_name: "Solar Plant",
          log_message: "Solar power upgrade applied",
          description: "Harness the power of the sun to generate energy.",
          order: 1,
          isVisible: false,
          isApplied: false,
          resourceCostUpdate: [{ resourceId: "money", name: "Money", quantity: 0.8 }],
          resourceCost: [{ unitId: "money", name: "Money", quantity: 800000 }],
          resourceOutputUpdate: [{ resourceId: "energy", name: "Energy", quantity: 15 }],
          requiredUnits: [],
          requiredResources: [{ unitId: "money", name: "Money", quantity: 500000 }],
        },
      ],
    },
  ],
};
